# Mirrors the commits of this repo to the Epitech repo
name: Mirroring

on:
  push:
    branches:
      - main   # déclenche le mirroring uniquement quand tu pushes sur main

jobs:
  to_epitech_github:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # on prend tout l’historique, pas juste le dernier commit

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:EpitechMscProPromo2028/T-WEB-500-digitalResume-NAN_clement-garreau.git
          ssh_private_key: ${{ secrets.EPITECH_MIRROR_SSH_KEY }}
